### ISSUE TITLE
Can you wrap the GTFS files into a ZIP file?

### ISSUE THREAD

**Issue by stevevance** [transportforcairo/Metro-GTFS#2]
I'd like to submit the Cairo GTFS feed your group created to the [Transitland Feed Registry](https://transit.land/feed-registry/) so that it can be integrated into a worldwide database of transit feeds. 

Transitland Feed Registry requires that the feed be hosted somewhere (GitHub is fine) as a ZIP file.

**Comment by transportforcairo** [comment]
Hi @stevevance , thank you for that. 

I pushed a new commit, and it has a zipped Archive.zip. 

Please let me know if it works now.

**Comment by Momomtaz** [comment]
Hi @stevevance great to hear. 

I see you already went ahead, and put the Metro feed online. Excellent! We will continue uploading updated datasets on the same Github, as we progressively release them.  

Having said that, I need to point out a small detail, and let's consider this an important point of discussion: The https://transit.land/feed-registry/operators/o-stq4-nationalauthorityfortunnels page does not mention the creator of the feed (us, or Transport for Cairo (TFC) ) at all. This goes against the attribution part of the license, technically. 

The reason is simple: In our case, the creator of the feed (Transport for Cairo) is not the operator of the system (National Authority for Tunnels). 

The reason I'm mentioning this is simple: I don't care about legal technicalities. I would however ask: Is there a possibility to accommodate for this situation in the Transit.land repository?

**Comment by stevevance** [comment]
Thanks for doing that @Momomtaz. 

Someone else created that Feed Registry entry, but I have updated the "Attribution text" section. 

I realized that the Transitland system doesn't need you to compile it into a ZIP file because your entire repo has the same contents of a ZIP file and we can grab the "master" branch of this repo as a ZIP file (which is what the Feed Registry entry shows was already happening).
